use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "RealWorld API",
        version = "1.0.0",
        description = "RealWorld API specification - A blogging platform API with authentication, articles, comments, and user profiles.\n\n**Authentication**: Many endpoints require a JWT token. Include the token in the Authorization header as `Token <jwt>`.",
    ),
    paths(
        crate::http::routes::auth::login,
        crate::http::routes::auth::register,
        crate::http::routes::users::get_current_user,
        crate::http::routes::users::update_user,
        crate::http::routes::profiles::get_profile,
        crate::http::routes::profiles::follow_user,
        crate::http::routes::profiles::unfollow_user,
        crate::http::routes::articles::list_articles,
        crate::http::routes::articles::feed_articles,
        crate::http::routes::articles::get_article,
        crate::http::routes::articles::create_article,
        crate::http::routes::articles::update_article,
        crate::http::routes::articles::delete_article,
        crate::http::routes::articles::favorite_article,
        crate::http::routes::articles::unfavorite_article,
        crate::http::routes::comments::get_comments,
        crate::http::routes::comments::create_comment,
        crate::http::routes::comments::delete_comment,
        crate::http::routes::tags::get_tags,
        crate::http::routes::health::health_check,
    ),
    components(schemas(
        crate::http::dto::login::LoginRequest,
        crate::http::dto::login::LoginUser,
        crate::http::dto::register::RegisterRequest,
        crate::http::dto::register::RegisterUser,
        crate::http::dto::user::UserResponse,
        crate::http::dto::user::UserData,
        crate::http::dto::user::UpdateUserRequest,
        crate::http::dto::user::UpdateUser,
        crate::http::dto::profile::ProfileResponse,
        crate::http::dto::profile::Profile,
        crate::http::dto::article::ArticlesResponse,
        crate::http::dto::article::ArticleResponse,
        crate::http::dto::article::ArticleListItem,
        crate::http::dto::article::ArticleItem,
        crate::http::dto::article::CreateArticleRequest,
        crate::http::dto::article::CreateArticle,
        crate::http::dto::article::UpdateArticleRequest,
        crate::http::dto::article::UpdateArticleQuery,
        crate::http::dto::article::ArticleListQuery,
        crate::http::dto::article::ArticleFeedListQuery,
        crate::http::dto::comment::CommentsResponse,
        crate::http::dto::comment::CommentResponse,
        crate::http::dto::comment::CommentItem,
        crate::http::dto::comment::CreateCommentRequest,
        crate::http::dto::comment::CreateComment,
        crate::http::dto::tag::TagsResponse,
        crate::http::dto::error::ErrorResponse,
        crate::http::dto::error::ErrorBody,
        crate::model::values::email::Email,
        crate::model::values::username::Username,
        crate::model::values::password::Password,
        crate::model::values::bio::Bio,
        crate::model::values::image::Image,
        crate::model::values::slug::Slug,
        crate::model::values::article_title::ArticleTitle,
        crate::model::values::article_description::ArticleDescription,
        crate::model::values::article_body::ArticleBody,
        crate::model::values::comment_body::CommentBody,
        crate::model::values::tag_name::TagName,
        crate::model::values::comment_id::CommentId,
        crate::model::limit::Limit,
        crate::model::offset::Offset,
    )),
    tags(
        (name = "Authentication", description = "User registration and login"),
        (name = "User", description = "Current user operations"),
        (name = "Profiles", description = "User profile viewing and following"),
        (name = "Articles", description = "Article CRUD operations and favorites"),
        (name = "Comments", description = "Article comment operations"),
        (name = "Tags", description = "Article tags"),
        (name = "Health", description = "Health check endpoint"),
    )
)]
pub struct ApiDoc;
